### ISSUE TITLE
Lỗi api key.

### ISSUE THREAD

**Issue by soibat** [appota/android-game-sdk#2]
Khi mình sử dụng api key trong app example của appota :da039a802fc030daadcc0ad0bd87392d05439f212
thì khi click vào các button Payment... nó bật được dialog login lên, nhưng khi login xong (G+, hoặc facebook, acc appota) thì khi click lại button Payment, nó chỉ hiện Toast (Loading...) rồi im luôn.

Mình đã tạo app trên appota và được cung cấp 4 key như trong hình. 
![capture](https://cloud.githubusercontent.com/assets/11373623/8611398/ae32c00c-26ea-11e5-84ec-bdcaa5f35c2c.PNG)
Mình đã thử dùng InApp api_key, thấy logcat báo 
sendEventLogSuccess﹕ {"status":true}
Tuy nhiên không có hiện dialog nào khi click các nút Payment...

Minh thấy key InApp api_key có cấu trúc khác api key của app example trong appota.
Vậy mình đăng ký app có bị sai gì không? tại sao api key của mình không thể sử dụng được?
Cảm ơn.

Logcat khi dùng api key của mình.
07-09 23:05:59.183    5162-5189/com.silverwolf.appotademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-09 23:05:59.183    5162-5189/com.silverwolf.appotademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa29454e0, error=EGL_SUCCESS
07-09 23:05:59.262    5162-5189/com.silverwolf.appotademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-09 23:05:59.262    5162-5189/com.silverwolf.appotademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa2a81480, error=EGL_SUCCESS
07-09 23:06:00.507    5162-5162/com.silverwolf.appotademo E/sendEvent﹕ Category:On Click,action:Click show payment,label:
07-09 23:06:00.523    5162-5162/com.silverwolf.appotademo I/﹕ Configuration URL is empty.. please wait..
07-09 23:06:00.578    5162-5189/com.silverwolf.appotademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-09 23:06:00.578    5162-5189/com.silverwolf.appotademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xaf035a20, error=EGL_SUCCESS
07-09 23:06:00.657    5162-5184/com.silverwolf.appotademo I/qtaguid﹕ Failed write_ctrl(u -1) res=-1 errno=9
07-09 23:06:00.658    5162-5184/com.silverwolf.appotademo I/qtaguid﹕ Untagging socket -1 failed errno=-9
07-09 23:06:00.658    5162-5184/com.silverwolf.appotademo W/NetworkManagementSocketTagger﹕ untagSocket(-1) failed with errno -9
07-09 23:06:00.661    5162-5162/com.silverwolf.appotademo E/sendEventLogSuccess﹕ {"status":true}

**Comment by n2a5me** [comment]
Chào bạn, mặc định khi tạo ứng dụng sẽ có cấu hình của SDK 3 do SDK 4 đang ở Developer Preview.
Bạn hãy cung cấp cho bên mình email để support bạn chuyển ứng dụng sang SDK4.

**Comment by soibat** [comment]
Chào bạn!
Email: touch.us@pix.com.vn
Ở SDK 3, khi sử dụng api key cũng không có hiện tượng gì xảy ra. Nhưng dùng api key của appota example thì vẫn bình thường.
Bạn xem giúp mình.
Cảm ơn.

**Comment by n2a5me** [comment]
Chào bạn,
Hỗ trợ bên mình sẽ support bạn trong thời gian nhanh nhất.
