### ISSUE TITLE
packageID lấy ở đâu?

### ISSUE THREAD

**Issue by soibat** [appota/android-game-sdk#3]
Trong code có sử dụng các hàm để hiển thị gói thanh toán. Nhưng mình không hiểu "app.pkid.tym4K" lấy ở đâu? Mình phải đăng ký nó ở đâu trong appota developer để nó nhận biết được gói thanh toán của người dùng?

    public void makePaymentPackage(View view){
        AppotaGameSDK.getInstance().showPaymentViewWithPackageID("app.pkid.tym4K");
    }

    public void makePaymentPackageCoin(View view){
        AppotaGameSDK.getInstance().showPaymentViewWithPackageID("app.pkid.coin100");
    }

Xin cảm ơn.

**Comment by n2a5me** [comment]
Chào bạn, app.pkid.tym4k là một trong những mã thanh toán được định nghĩa bởi developer thao tác trên trang web sdk tool chứa cấu hình các loại thanh toán, mã gói thanh toán...
Bạn hãy cung cấp cho bên mình email để support bạn.

**Comment by soibat** [comment]
Cảm ơn bạn. Mình đã tìm được nơi add Item.
